blank_issues_enabled: false

contact_links:
  - name: Questions & Discussions ğŸ’¬
    url: https://github.com/SamErde/PSPrettier/discussions
    about: Please use GitHub discussions for any questions.
  - name: Documentation ğŸ“š
    url: https://day3bits.com/PSPrettier
    about: Documentation for the PSPrettier project.
  - name: ReadTheDocs ğŸ“– (Alternate/Backup Documentation Site)
    url: https://psprettier.readthedocs.io/en/latest/
    about: ReadTheDocs for the PSPrettier project.
#  - name: Basic FAQs â“
#    url: https://github.com/SamErde/PSPrettier/wiki/FAQs
#    about: Answers to the Basic Frequently Asked Questions
